### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by sam1e-dev** [Wizz1337/TikTokMassViewbotting#3]
This could work again if you would put proxy rotation from text file maybe? Correct me if im wrong but i think that could fix it

**Comment by Wizz1337** [comment]
yep i will check

**Comment by Wizz1337** [comment]
can i get your telegram ?

**Comment by sam1e-dev** [comment]
sure its @jdysk but i prefer discord sam1e#7777 if you dont mind but otherwise it doesnt matter :D

**Comment by sam1e-dev** [comment]
oops, mb its @sam1eee actually

**Comment by andress134** [comment]
Adding the proxy function is useless.
Because it will spam and your requests are received from IPs without a useragent (the agent user must be dynamic) and many other functions

If you want something that makes "real" views without risking closing your account or deleting video, and that would really help with promotion.

It would be a script based on browser emulator, traffic source to be spoofed, random useragents, etc.
timeout so you don't spam with views, because it's useless 

a good tool is if someone can create a tool like this https://hackforums.net/showthread.php?tid=6197797

**Comment by Wizz1337** [comment]
its useless to use tiktok tokens and other shit bcs the api used is not a public api 
and i made a really cool one request look real
with a ton of useragent <3
(i will post soon)

**Comment by Wizz1337** [comment]
Upload new version
